# Generated by Django 3.2.4 on 2021-06-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeyearassociation',
            name='level',
        ),
        migrations.AlterField(
            model_name='gradeyearassociation',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14)]),
        ),
    ]
