# Generated by Django 3.2.4 on 2021-06-30 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210629_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeyearassociation',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.year'),
            preserve_default=False,
        ),
    ]
